name: Publish Package to NPM (Self-Hosted)

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish:
    name: Build & Publish to NPM
    runs-on: [self-hosted]
    steps:
      - name: Recuperation du code source
        uses: actions/checkout@v4

      - name: Configuration du token NPM
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Installation des dependances
        run: npm ci

      - name: Compilation TypeScript
        run: npm run build

      - name: Publication sur le registre NPM
        run: npm publish --access public
